# main text of home
title: Tyler Hudson
bio: Aspiring DevOps Engineer

# twitter summary info
description: Blog/Portfolio website showing my thoughts and what I'm working on.

# if it's an external image, update below for true
# better with square images
external-image: true
picture: https://avatars.githubusercontent.com/u/105871355?s=400&u=461c65b3cc190be57a8183b2c3f54d2cb56c20db&v=4

# your site color theme, true for dark theme, 
# false to light theme, auto to switch with system.
dark-theme: true

resume: true
resume-external: true
resume-url: tkhudson.github.io\assets\images\tylerhudson_resume_4.pdf

url: https://tylerkhudson.com/

permalink: /:title/

# To enable google analytics, supply your token below
# analytics-google: 'UA-MYANALYTICS'

# if you don't want comments in your posts, leave categories empty
disqus:
  shortname: github # enter this from your disqus account
  categories: [blog, project] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
# facebook: myfacebook
twitter: tylerkhudson
# instagram: myinstagram
linkedin: tyler-k-hudson
github: tkhudson
email: tylerkhudson@gmail.com

authors:
  Tyler:
    name: Tyler
    bio: 
    external-image: false
    picture: https://avatars.githubusercontent.com/u/105871355?v=4
    twitter: tyler-k-hudson

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# if you don't need projects, comment the *projects* configs below
projects: true

# if you don't need "about" or "blog", comment them out below
about: true
blog: true

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: true

# add default values to specific pages or layouts
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      layout: "post"
    values:
      # setting all post to not hidden by default,
      # can be overridden in the front matter for a specific post
      hidden: false

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji

compress_html:
  ignore:
    envs:
      - development
      - stage

exclude:
  [
    "README.md",
    "Gemfile",
    "Gemfile.lock",
    "FAQ.md",
    "vendor",
  ]
